<?php 
$mensaje = $this->mensaje;
$$nombreUsuario = $this->nombreUsuario;
$contrasena = $this->contrasena;

?>

<div class="features_items"><!--features_items-->
    <h1 class="col-lg-12 title text-center"><a href="<?php echo $this->basePath();?>/inicio/inicio" >SISTEMA DE GESTIÓN PARROQUIAL</a> </h1>
    <div class="col-sm-4"></div>
    <div class="login-form col-sm-4 text-center">
            <h2><i>Ingresa a tu cuenta</i></h2>
            <div id="mensaje"><?php echo $mensaje;?></div>
            <form action="<?php echo $this->basePath();?>/inicio/inicio" method="post" id="formLogin">
                <div class="form-group has-feedback">
                    <input autofocus="true" type="text" class="form-control" id="nombreUsuario" value="<?php echo $nombreUsuario;?>" name="nombreUsuario" placeholder="Usuario" autocomplete="off">
                    <span class="fa fa-user form-control-feedback"></span>
                </div>
                <div class="form-group has-feedback">
                    <input type="password" class="form-control" id="contrasena" name="contrasena" value="<?php echo $contrasena;?>" autocomplete="off" placeholder="Contraseña">
                    <span class="fa fa-key form-control-feedback"></span>
                </div>
                <button type="submit" id="btnIniciar" name="btnIniciar" data-loading-text="Iniciando..." class="btn btn-default pull-right button login-form">Iniciar</button>
            </form>
    </div>
    <div class="col-sm-4"></div>
</div>