<?php 
echo $this->doctype(); 
use Zend\Session\Container;
$sesionUsuario = new Container('sesionparroquia');
if($sesionUsuario->offsetExists('idUsuario')){
?>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SGP</title>
    <link rel="icon" type="image/png" href="<?php echo $this->basePath();?>/public/librerias/images/pagina/logoiglesia.png" />
        <!-- Le styles -->
        <?php echo $this->headLink()
                
                ->prependStylesheet($this->basePath() . '/public/librerias/css/jquery.dataTables.min.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/plugins/daterangepicker/daterangepicker.css')
                
                
                ->prependStylesheet($this->basePath() . '/public/librerias/plugins/datepicker/datepicker3.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/plugins/jvectormap/jquery-jvectormap-1.2.2.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/plugins/morris/morris.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/plugins/iCheck/flat/blue.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/dist/css/skins/_all-skins.min.css')
               
                ->prependStylesheet($this->basePath() . '/public/librerias/dist/css/AdminLTE.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css')
                ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/bootstrap/css/bootstrap.min.css');
                ?>
        

                        <?php echo $this->headScript()  
                ->prependFile($this->basePath() . '/public/librerias/js/jquery.dataTables.min.js')   
                ->prependFile($this->basePath() . '/public/librerias/js/jquery.form.js')   
                ->prependFile($this->basePath() . '/public/librerias/dist/js/demo.js') 
                ->prependFile($this->basePath() . '/public/librerias/dist/js/app.min.js') 
                ->prependFile($this->basePath() . '/public/librerias/plugins/fastclick/fastclick.js') 
                ->prependFile($this->basePath() . '/public/librerias/plugins/slimScroll/jquery.slimscroll.min.js') 
                ->prependFile($this->basePath() . '/public/librerias/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') 
                ->prependFile($this->basePath() . '/public/librerias/plugins/datepicker/bootstrap-datepicker.js') 
                ->prependFile($this->basePath() . '/public/librerias/plugins/knob/jquery.knob.js')   
                ->prependFile($this->basePath() . '/public/librerias/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')   
                ->prependFile($this->basePath() . '/public/librerias/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js') 
                ->prependFile($this->basePath() . '/public/librerias/plugins/sparkline/jquery.sparkline.min.js')   
                ->prependFile($this->basePath() . '/public/librerias/bootstrap/js/bootstrap.min.js')   
                ->prependFile($this->basePath() . '/public/librerias/plugins/jQuery/jquery-2.2.3.min.js'); ?>
    </head>
    
    <body class="hold-transition skin-blue sidebar-mini">
        <style type="text/css">
            input {
                font-weight: bold;
            }

            label {
                font-weight: bold;
            }
            select {
                font-weight: bold;
            }
            option {
                font-weight: bold;
            }
            textarea {
                font-weight: bold;
            }
/*            td {
                font-weight: bold;
            }*/
        </style>
        <style type="text/css">
            table tr th{
                text-align: center;
                
            }
            
        </style>
        <script type="text/javascript">
            function validarNumeros(vari) {
                $('#' + vari).on('input', function () {
                    this.value = this.value.replace(/[^0-9]/g, '');
                });

            }
        </script>
        <script type="text/javascript">
        function validarNumerosR(vari) {
            $('#' + vari).on('input', function () {
                this.value = this.value.replace(/[^0-9]/g, '');
                if($("#"+vari).val() > 100){
                    $("#"+vari).val(100);
                }
            });
        }
    </script>
        <div class="wrapper">
            <header class="main-header">
                <a style="position: fixed;" href="<?php echo $this->basePath();?>/administrador/inicio" class="logo">
                    <span class="logo-mini"><b>SWGP</b></span>
                    <span class="logo-lg"><b>SWGP</b></span>
                </a>
                <nav class="navbar navbar-fixed-top">
                    <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                      <span class="sr-only">Toggle navigation</span>
                    </a>
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav" id="contenedorMenuCliente">
                            <li><a href="<?php echo $this->basePath();?>/administrador/miperfil"><b><?php echo $sesionUsuario->offsetGet('nombres')?></b></a></li>
                        </ul>
                    </div>
                </nav>
            </header>
            <style type="text/css">
                .stuck {
                   position: fixed;
                    top: 10px;
                    left: 10px;
                    bottom: 10px;
                    overflow-y: auto;
                }
            </style>
            <aside class="main-sidebar stuck">
                <section class="sidebar">
                    <div class="">
                        <div class="">
                            <img style="width: 90%;" src="<?php echo $this->basePath();?>/public/librerias/images/pagina/logoiglesia.png">
                        </div>
                    </div>
                    <?php
                       echo  $sesionUsuario->offsetGet('menu_slide');
                    ?>
<!--                    <ul class="sidebar-menu">
                        <li class="header">OPCIONES</li>
                        <li>
                            <a href="<?php echo $this->basePath();?>/administrador/direcciones" ><i class="fa fa-asterisk"></i><span>DIRECCIONES</span></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath();?>/administrador/personas" ><i class="fa fa-user"></i><span>PERSONAS</span></a>
                        </li>
                        <li>
                            <a href="<?php echo $this->basePath();?>/administrador/sacerdotes" ><i class="fa fa-user"></i><span>SACERDOTES</span></a>
                        </li>
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-table"></i> <span>MISAS</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu" style="display: none;">
                                <li>
                                    <a  href="<?php echo $this->basePath();?>/administrador/lugaresmisa" ><i class="fa fa-map"></i><span>LUGARES</span></a>
                                </li>
                                <li>
                                    <a  href="<?php echo $this->basePath();?>/administrador/misas" ><i class="fa fa-maxcdn"></i><span>MISAS</span></a>
                                </li>
                                <li>
                                    <a  href="<?php echo $this->basePath();?>/administrador/configurarmisas" ><i class="fa fa-cogs"></i><span>CONFIGURAR MISAS</span></a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a  href="<?php echo $this->basePath();?>/inicio/salir" ><i class="fa fa-sign-out"></i><span>SALIR</span></a>
                        </li>
                    </ul>-->
                </section>
            </aside>
         
            
            <div id="rutaBase"><?php echo $this->basePath();?></div>
            <?php echo $this->content; ?>
            
            <footer class="main-footer">
                <div class="pull-right hidden-xs">
                    <b>Versión</b> 1.0.0
                </div>
                <strong>Sistema web de gestión parroquial.</strong>
            </footer>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>          
</html>
<?php
}else{
?>
   <script>window.location='<?php echo $this->basePath();?>/inicio/inicio'</script>";
<?php } ?>