<?php 
echo $this->doctype(); 
use Zend\Session\Container;
$sesionUsuario = new Container('sesionparroquia');
if(!$sesionUsuario->offsetExists('idUsuario')){
?>
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SGP</title>
    <link rel="icon" type="image/png" href="<?php echo $this->basePath();?>/public/librerias/images/pagina/logoiglesia.png" />
        <!-- Le styles -->
        <?php echo $this->headLink()
                ->prependStylesheet($this->basePath() . '/public/librerias/css/responsive.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/css/main.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/css/animate.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/css/price-range.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/css/prettyPhoto.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/css/font-awesome.min.css')
                ->prependStylesheet($this->basePath() . '/public/librerias/css/bootstrap.min.css');
                ?>
        

                <?php echo $this->headScript()  
                ->prependFile($this->basePath() . '/public/librerias/js/jquery.form.js')   
                ->prependFile($this->basePath() . '/public/librerias/js/main.js')   
                ->prependFile($this->basePath() . '/public/librerias/js/jquery.prettyPhoto.js')   
                ->prependFile($this->basePath() . '/public/librerias/js/price-range.js')   
                ->prependFile($this->basePath() . '/public/librerias/js/jquery.scrollUp.min.js') 
                ->prependFile($this->basePath() . '/public/librerias/js/bootstrap.min.js')   
                ->prependFile($this->basePath() . '/public/librerias/js/jquery-2.1.1.min.js');
                header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1
                header("Expires: Sat, 1 Jul 2000 05:00:00 GMT"); // Fecha en el pasado ?>
    
    </head>
    
    <body>
        <style type="text/css">
            .bordeImagen{
                background:none;
            }

            .bordeImagen:hover{
                background:  #2c4762;
            }
            
        </style>
    <header id="header"><!--header-->
		
        <div class="header-middle"><!--header-middle-->
            <div class="container">
                <div class="row">
<!--                    <div class="col-sm-4">
                        <div class="logo pull-left">
                            <a href="<?php echo $this->basePath();?>/inicio/inicio"><h2><strong>SGP</strong></h2></a>
                        </div>
                    </div>
                    <div class="col-sm-8">
                    </div>-->
                </div>
            </div>
        </div>
    </header>
  
    
    <?php echo $this->content; ?>
        
    <footer id="footer"><!--Footer-->
        <div class="footer-top">
<!--            <div class="container">
                <div class="row">
                    <div class="col-sm-2">
                        <div class="companyinfo">
                            <h2><span>SGP</span></h2>
                            <p>Sistema de gestión parroquial</p>
                        </div>
                    </div>
                    <div class="col-sm-7">

                    </div>
                    <div class="col-sm-3">
                        <div class="address">
                            <img src="<?php echo $this->basePath();?>/public/librerias/images/pagina/logoiglesia2.png" alt="">
                            <p>Ecuador</p>
                        </div>
                    </div>
                </div>
            </div>-->
        </div>
		
        <div class="footer-widget">
            
        </div>
		
        <div class="footer-bottom">
            <div class="container">
                <div class="col-sm-12 text-center">
                    <div class="companyinfo">
                        <p> © 2018 Unidad de Producción de Software. 
                            Todos los Derechos Reservados | Desarrollado por 
                            <a target="_blank" href="https://github.com/dayubadel"> Bailón D. Dayana </a> &
                            <a target="_blank" href="https://github.com/chavomacias"> Macías I. Nel </a> 
                        </p>
                    </div>
                </div>
            </div>
        </div>
		
    </footer>      
        <?php echo $this->inlineScript() ?>
    </body>          
</html>
<?php
}else if($sesionUsuario->offsetExists('idUsuario')){
?>  
    <script>window.location='<?php echo $this->basePath();?>/administrador/inicio'</script>";
<?php } ?>
    
