<?php
$validacionPrivilegio = $this->validacionPrivilegio;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/administrativos/administrativos.php');
  include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/cargosadministrativos/cargosadministrativos.php');
?>

<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            Administrativos
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true)
        {
        ?>
    <section class="">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresoResponsable"> </div>
                    <form onKeypress="if(event.keyCode == 13) event.returnValue = false;"  onsubmit="return validarIngresoResponsable(this)" id="formIngresoResponsable" method="post" action="<?php echo $this->basePath();?>/administrativos2/ingresaradministrativo">
                        <div class="form-group col-lg-6">
                            <label for="identificacion">IDENTIFICACIÓN</label>
                            <input onkeyup="filtrarAdministrativoPorIdentificacion(event);" onkeydown="validarNumeros('identificacion');" maxlength="10" autocomplete="off" autofocus="" type="text" id="identificacion" name="identificacion" class="form-control">
                        </div>


                        <div class="form-group col-lg-6" id="contenedorDatosResponsable">

                        </div>
                   
                    </form>
                </div>
            </div>
        </div>
    </section>
       <?php  }  ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row">
                <div id="mensajeTablaResponsables">
                    
                </div>
                <div  class="col-lg-12">
                    <div id="contenedorTablaResponsables"></div>
                </div>
            </div>
        </div>
    </section>
    
     <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaCargosAdministrativos"> </div>
                    <div class="form-group col-lg-5">
                    <form onKeypress="if(event.keyCode == 13) event.returnValue = false;"  onsubmit="return validarIngresoCargo(this)" id="formIngresoCargo" method="post" action="<?php echo $this->basePath();?>/cargosadministrativos/ingresarcargoadministrativo">
                      
                            <label for="cargo">NUEVO CARGO</label>
                            <input autocomplete="off" type="text" id="nombreCargo" name="nombreCargo" class="form-control">
                            <br>
                            <button data-loading-text="GUARDANDO..." id="btnGuardarCargo" type="submit" class="btn btn-primary pull-right"><i class="fa fa-save"></i>GUARDAR CARGO</button>
                   

                   
                    </form>
                    </div>
               
                <div  class="col-lg-7">
                    <div id="contenedorTablaCargosAdministrativos"></div>
                </div>
                </div>
              </div>
            </div>
    </section>
    
</div>
<script type="text/javascript">
$(document).ready(function(){
    cargandoAdministrativos('#contenedorTablaResponsables');
    CargarAdministrativos();
    
});

</script>