<?php
//estas librerias php son llamadas ya que contienen los metodos ajax para obtener y envias
//datos al respectivo controlador
$optionPeriodos = $this->optionPeriodos;
include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/asistencias/asistencias.php');

 ?>


<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            Asistencia
            <small>SWGP</small>
        </h1>
    </section>
    
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                   
                    <div class="col-lg-12 ">
                        <div id="mensajeContenedorHorarioAsistencia"></div>
                        <div class="form-group col-lg-4" id="contenedorSeleccionarPeriodo">
                            <label for="selectPeriodoAsistencia">PERIODO</label>
                            <select onchange="filtrarlistaCursosPorPeriodo();" class="form-control" id="selectPeriodoAsistencia" name="selectPeriodoAsistencia">
                            <?php echo $optionPeriodos;?>
                            </select>
                        </div>  
                        <div class="form-group col-lg-4" id="contenedorlistacursosAsistencia"> </div>
                        <div class="form-group col-lg-4" id="contenedorlistahorariosAsistencia"> </div>
                        <div class="form-group col-lg-6 col-md-6" id="contenedorInfoGeneralHorarioSeleccionadoAsistencia"> </div>
                        <div class="form-group col-lg-6 col-md-3" id="contenedorHorarioSeleccionadoAsistencia" ></div>   
                        <div class="form-group col-lg-6 col-md-3" id="contenedorOpcionesAsistencia" ></div> 
                       
                    </div>
                
                <div class="col-lg-12 " >
                    <div id="mensajeContenedorListaAsistencia">  
                    </div>                  
                    <div class="form-group col-lg-6" id="contenderListaFechaAsistencia"></div>
                    <div class="form-group col-lg-6" ></div>
                    <div class="form-group col-lg-12" id="contenedorContenedorListaAsistencia"> </div>
                         
                </div>
            </div>
        </div>
    </section>
    
    
    
    
</div>