<?php
$validacionPrivilegio = $this->validacionPrivilegio;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/bautismo/obtenerdireccionesselect.php');
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/bautismo/bautismo.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            BAUTISMO
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true)
        {
            $optionPersona = $this->optionPersona;
            $optionHombres = $this->optionHombres;
            $optionMujeres = $this->optionMujeres;
        ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresarBautismo"> </div>
                    <form onKeypress="if(event.keyCode == 13) event.returnValue = false;"  onsubmit="return validarIngresoBautismo(this)" method="post" action="<?php echo $this->basePath()?>/bautismo/ingresarbautismo" id="formIngresarBautismo">
                        <div class="col-lg-6 form-group">
                            <label for="nombres">APELLIDOS Y NOMBRES BAUTIZADO</label>
                            <input onchange="$('#contenedorRestoDelFormulario').html('');" list="buscado" id="nombres" autocomplete="off" name="nombres" type="text" class="form-control" placeholder="Buscar">
                            <datalist id="buscado">
                                <?php echo $optionPersona; ?>
                            </datalist>
                        </div> 
                        <div class="col-lg-6 form-group">
                            <label for="fechaNacimiento">FECHA DE NACIMIENTO</label>
                            <input type="date" id="fechaNacimiento" name="fechaNacimiento" class="form-control" >
                        </div>
                        <div class="col-lg-12 form-group">
                            <button onclick="filtrarPersonaPorNombres();" type="button" id="btnBuscarPersona" data-loading-text="BUSCANDO..." class="btn  btn-primary btn-flat pull-right"><i class="fa fa-search"></i>BUSCAR</button>
                        </div>
                        
                        <div id="contenedorRestoDelFormulario" class="col-lg-12">

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
       <?php } ?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaBautismo"> </div>
                    <div id="contenedorTablaBautismo"></div>
                </div>
            </div>
        </div>
    </section>
</div>



<script type="text/javascript">  
$(document).ready(function(){
    cargandoBautismo("#contenedorTablaBautismo");
   obtenerBautismos(); 
});


</script>
    