<?php
$optionSelectPeriodos = $this->optionSelectPeriodos;
$optionSelectCurso = $this->optionSelectCurso;
$optionSelectDocentes = $this->optionSelectDocentes;
$validacionPrivilegio = $this->validacionPrivilegio;
$validarRangoAsistencia = $this->validarRangoAsistencia;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/configurarcurso/configurarcurso.php');
// include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/configurarmisas/sacerdotes.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            CONFIGURAR CURSOS
            <small>SWGP</small>
        </h1>
    </section>
        <?php
        if($validacionPrivilegio==true && $validarRangoAsistencia == TRUE)
        {
        ?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresarConfigurarCurso"> </div>
                    <form  method="post" action="<?php echo $this->basePath()?>/configurarcurso/ingresarconfigurarcurso" id="formIngresarConfigurarCurso">
                        <div class="col-lg-4 form-group">
                            <label for="selectPeriodo">SELECCIONE UN PERIODO</label>
                            <select  class="form-control" id="selectPeriodo" name="selectPeriodo">
                                <?php echo $optionSelectPeriodos;?>
                            </select>
                        </div> 
                        <div class="col-lg-4 form-group">
                            <label for="selectCurso">SELECCIONE UNA CURSO</label>
                            <select class="form-control" onchange="filtrarDatosCurso();" id="selectCurso" name="selectCurso">
                                <?php echo $optionSelectCurso;?>
                            </select>
                        </div> 
                        <div class="col-lg-4 form-group">
                            <label for="selectDocente">SELECCIONE UN DOCENTE</label>
                            <select class="form-control" id="selectDocente" name="selectDocente">
                                <?php echo $optionSelectDocentes;?>
                            </select>
                        </div> 
                        <div class="col-lg-4 form-group">
                            <label for="fechaInicioMatricula">FECHA INICIO MATRÍCULA</label>
                            <input type="date" id="fechaInicioMatricula" name="fechaInicioMatricula" class="form-control">
                        </div>
                        <div class="col-lg-4 form-group">
                            <label for="fechaFinMatricula">FECHA FÍN MATRÍCULA</label>
                            <input type="date" id="fechaFinMatricula" name="fechaFinMatricula" class="form-control">
                        </div>
                        <div class="col-lg-4 form-group">
                            <label for="cupos">CUPOS</label>
                            <input type="text" onkeydown="validarNumeros('cupos')" min="1" max="100" step="1" id="cupos" name="cupos" class="form-control">
                        </div>
                        <div class="col-lg-4 form-group">
                            <label for="fechaInicio">FECHA INICIO</label>
                            <input type="date" id="fechaInicio" name="fechaInicio" class="form-control">
                        </div>
                        <div class="col-lg-4 form-group">
                            <label for="fechaFin">FECHA FÍN</label>
                            <input type="date" id="fechaFin" name="fechaFin" class="form-control">
                        </div>
                        <div class="col-lg-4 form-group">
                            <label for="valor">VALOR</label>
                            <input type="number" step="0.01" min="0.00" max="100.00" id="valor" name="valor" class="form-control">
                        </div>
                        <div class="col-lg-12 form-group">
                            <div id="mensajeContenedorDatosCurso"></div>
                            <div class="col-lg-4"></div>
                            <div id="contenedorDatosCurso" class="col-lg-4"></div>
                            <div class="col-lg-4"></div>
                        </div> 
                    </form>
                </div>
            </div>
        </div>
    </section>
           <?php }else{ ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div class="alert alert-danger text-center" role="alert">NO SE HA ESTABLECIDO UN PORCENTAJE MÍNIMO DE ASISTENCIA POR FAVOR ESTABLÉSCALO</div>
                </div>
            </div>
        </div>
    </section>
       <?php }?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaConfigurarCurso"> </div>
                    <div id="contenedorTablaConfigurarCurso" class="col-lg-9"></div>
                     <div id="contenedorTablaHorario" class="col-lg-3"></div>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">
$(document).ready(function(){
    cargandoConfigurarCurso('#contenedorTablaConfigurarCurso');
    obtenerConfigurarCurso();
});

</script>
