<?php
$validacionPrivilegio = $this->validacionPrivilegio;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/cursos/cursos.php');
// include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/direcciones/obtenerdireccionesselect.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            CURSOS
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true)
        {
        ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresarCurso"> </div>
                    <form method="post" action="<?php echo $this->basePath()?>/cursos/ingresarcurso" id="formIngresarCurso">
                        <div class="form-group col-lg-6">
                            <label for="nombreProvincia">NOMBRE DEL CURSO</label>
                            <div class="input-group margin">
                                <input autofocus=""  type="text" id="descripcionCurso" name="descripcionCurso" class="form-control">
                                <span class="input-group-btn">
                                    <button style="margin-left: 10%;" name="btnGuardarCurso" id="btnGuardarCurso" data-loading-text="GUARDANDO.." class="btn  btn-primary btn-flat"><i class="fa fa-save"></i>GUARDAR</button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
       <?php } ?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaCurso"> </div>
                    <div id="contenedorTablaCurso"></div>
                </div>
            </div>
        </div>
    </section>
</div>



<script type="text/javascript">  
$(document).ready(function(){
    cargandoCursos("#contenedorTablaCurso");
   obtenerCursos(); 
});


</script>
    