<?php
$validacionPrivilegio = $this->validacionPrivilegio;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/docentes/docentes.php');
// include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/personas/direccionpersona.php');
?>

<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            Catequistas
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true)
        {
        ?>
    <section class="">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresoDocente"> </div>
                    <form onKeypress="if(event.keyCode == 13) event.returnValue = false;"  onsubmit="return validarIngresoDocente(this)" id="formIngresoDocente" method="post" action="<?php echo $this->basePath();?>/docentes/ingresardocente">
                        <div class="form-group col-lg-6">
                            <label for="identificacion">IDENTIFICACIÓN</label>
                            <input onkeyup="filtrarDocentePorIdentificacion(event);" onkeydown="validarNumeros('identificacion');" maxlength="10" autocomplete="off" autofocus="" type="text" id="identificacion" name="identificacion" class="form-control">
                        </div>


                        <div class="form-group col-lg-6" id="contenedorDatosDocente">

                        </div>
                   
                    </form>
                </div>
            </div>
        </div>
    </section>
       <?php } ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row">
                <div id="mensajeTablaDocente">
                    
                </div>
                <div  class="col-lg-12">
                    <div id="contenedorTablaDocente"></div>
                </div>
            </div>
        </div>
    </section>
    
</div>
<script type="text/javascript">
$(document).ready(function(){
    cargandoDocentes('#contenedorTablaDocente');
    obtenerDocentes();
});

</script>