<?php

$optionSelectCurso = $this->optionSelectCurso;

$validacionPrivilegio = $this->validacionPrivilegio;

 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/horarios/horarios.php');
// include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/configurarmisas/sacerdotes.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            CONFIGURAR HORARIOS
            <small>SWGP</small>
        </h1>
    </section>
        
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormHorarios"> </div>
                    <div class="col-lg-4 form-group">
                        <label for="selectCurso">SELECCIONE UN CURSO</label>
                        <select onchange="cargandoHorarios('#contenedorTablaHorarios');filtrarHorariosPorCurso();" class="form-control" id="selectCurso" name="selectCurso">
                            <?php echo $optionSelectCurso;?>
                        </select>
                    </div> 
                    <div class="col-lg-12 ">
                        <div id="mensajeTablaHorarios"> </div>
                        <div id="contenedorTablaHorarios"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
          

    <?php
        if($validacionPrivilegio==true)
        {
        ?>
    
    <div class="example-modal">
        <div class="modal " id="modalIngresarHoraHorario">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="contenedorTitulo">INGRESAR HORAS</h4>
                    </div>
                    <div class="modal-body">
                        <div id="mensajeFormHoraHorario">

                        </div>
                        <form method="post" action="<?php echo $this->basePath();?>/horarios/ingresarhorahorario" id="formIngresarHoraHorario">
                            <input type="hidden" id="idHorarioEncriptado" name="idHorarioEncriptado">
                            <div class="form-group col-lg-6">
                                <label for="horaInicio">HORA INICIO</label>
                                <input id="horaInicio" name="horaInicio" type="time" class="form-control" >
                            </div>
                            <div class="form-group col-lg-6">
                                <label for="horaFin">HORA FÍN</label>
                                <input id="horaFin" name="horaFin" type="time" class="form-control" >
                            </div>
                            <div class="form-group col-lg-12">
                                <button id="btnGuardarHoraHorario" data-loading-text="GUARDANDO..." class="btn btn-primary btn-flat pull-right" type="submit"><i class="fa fa-save"></i>GUARDAR</button>
                            </div>
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary pull-right btn-flat" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
    
     <?php } ?>
    
    
</div>

