<?php
$validacionPrivilegio = $this->validacionPrivilegio;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/matrimonio/obtenerdireccionesselect.php');
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/matrimonio/matrimonio.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            MATRIMONIO
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true)
        {
            $optionHombres = $this->optionHombre;
            $optionMujeres = $this->optionMujer;
        ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresarMatrimonio"> </div>
                    <form onKeypress="if(event.keyCode == 13) event.returnValue = false;" onsubmit="return validarIngresoMatrimonio(this)" method="post" action="<?php echo $this->basePath()?>/matrimonio/ingresarmatrimonio" id="formIngresarMatrimonio">
                        <h4>DATOS DE LOS ESPOSOS</h4>
                        <div class="col-lg-6 form-group">
                            <label for="identificacionEsposo">IDENTIFICACIÓN DEL ESPOSO</label>
                            <input onkeyup="filtrarPersonaPorIdentificacion(event,'identificacionEsposo','contenedorDatosEsposo');" onkeydown="validarNumeros('identificacionEsposo')" maxlength="10" autocomplete="off" autofocus="" type="text" id="identificacionEsposo" name="identificacionEsposo" class="form-control">
                            <div id="contenedorDatosEsposo"></div>
                        </div>
                        <div class="col-lg-6 form-group">
                            <label  for="identificacionEsposa">IDENTIFICACIÓN DE LA ESPOSA</label>
                            <input onkeyup="filtrarPersonaPorIdentificacion(event,'identificacionEsposa','contenedorDatosEsposa');" onkeydown="validarNumeros('identificacionEsposa')" maxlength="10" autocomplete="off" autofocus="" type="text" id="identificacionEsposa" name="identificacionEsposa" class="form-control">
                            <div id="contenedorDatosEsposa"></div>
                        </div>
                        
                        
                        <div class="col-lg-12 form-group">
                            <button onclick="filtrarMatrimonioPorEsposoEsposa();" type="button" id="btnBuscarPersona" data-loading-text="BUSCANDO..." class="btn  btn-primary btn-flat pull-right"><i class="fa fa-search"></i>BUSCAR</button>
                        </div>
                        
                        <div id="contenedorRestoDelFormulario" class="col-lg-12">

                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
       <?php } ?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaMatrimonio"> </div>
                    <div id="contenedorTablaMatrimonio"></div>
                </div>
            </div>
        </div>
    </section>
</div>



<script type="text/javascript">  
$(document).ready(function(){
    cargandoMatrimonio("#contenedorTablaMatrimonio");
    obtenerMatrimonios(); 
});


</script>
    