<?php
$validacionPrivilegio = $this->validacionPrivilegio;
 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/periodos/periodos.php');
// include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/direcciones/obtenerdireccionesselect.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            PERIODOS
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true)
        {
        ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresarPeriodo"> </div>
                    <form method="post" action="<?php echo $this->basePath()?>/periodos/ingresarperiodo" id="formIngresarPeriodo">
                        <div class="form-group col-lg-4">
                            <label for="descripcionPeriodo">NOMBRE DEL PERIODO</label>
                            <input autofocus=""  type="text" id="descripcionPeriodo" name="descripcionPeriodo" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label for="fechaIncio">FECHA INICIO</label>
                            <input  type="date" id="fechaInicio" name="fechaInicio" class="form-control">
                        </div>
                        <div class="form-group col-lg-4">
                            <label for="fechaFin">FECHA FÍN</label>
                            <input type="date" id="fechaFin" name="fechaFin" class="form-control">
                        </div>
                        <div class="form-group col-lg-12">
                            <button  name="btnGuardarPeriodo" id="btnGuardarPeriodo" data-loading-text="GUARDANDO.." class="btn  btn-primary btn-flat pull-right"><i class="fa fa-save"></i>GUARDAR</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
       <?php } ?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaPeriodos"> </div>
                    <div id="contenedorTablaPeriodos"></div>
                </div>
            </div>
        </div>
    </section>
</div>



<script type="text/javascript">  
$(document).ready(function(){
    cargandoPeriodos("#contenedorTablaPeriodos");
   obtenerPeriodos(); 
});


</script>
    