<?php
$validacionPrivilegio = $this->validacionPrivilegio;

 include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/rangoasistencia/rangoasistencia.php');
// include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/direcciones/obtenerdireccionesselect.php');
 ?>
<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            RANGO DE ASISTENCIA
            <small>SWGP</small>
        </h1>
    </section>
    <?php
        if($validacionPrivilegio==true )
        {
        ?>
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresarRango"> </div>
                    <form method="post" action="<?php echo $this->basePath()?>/rangoasistencia/ingresarrangoasistencia" id="formIngresarRangoAsistencia">
                        <div class="form-group col-lg-6">
                            <label for="nombreProvincia">INGRESE UN MÍNIMO DE ASISTENCIA (%)</label>
                            <div class="input-group margin">
                                <input autofocus="" onkeydown="validarNumerosR('porcentaje')"  type="text"  maxlength="3" id="porcentaje" name="porcentaje" class="form-control">
                                <span class="input-group-btn">
                                    <button style="margin-left: 10%;" id="btnGuardarRango" data-loading-text="GUARDANDO.." class="btn  btn-primary btn-flat"><i class="fa fa-save"></i>GUARDAR</button>
                                </span>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    
    
       <?php } ?>
   
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeTablaRangoAsistencia"> </div>
                    <div id="contenedorTablaRangoAsistencia"></div>
                </div>
            </div>
        </div>
    </section>
</div>



<script type="text/javascript">  
$(document).ready(function(){
    cargandoRangoAsistencia("#contenedorTablaRangoAsistencia");
   obtenerRangoAsistencia(); 
});


</script>
    