<?php
//estas librerias php son llamadas ya que contienen los metodos ajax para obtener y envias
//datos al respectivo controlador
$validacionPrivilegio = $this->validacionPrivilegio;
include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/usuarios/usuarios.php');
include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/usuarios/modulosprivilegios.php');
include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/usuarios/buscarpersona.php');

 ?>


<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            Usuarios
            <small>SWGP</small>
        </h1>
    </section>
    
    <?php
        if($validacionPrivilegio==true)
        {
        ?>
    <section class="">
        <div class="box-body nav-tabs-custom">
            <div class="row ">
                <div class="col-lg-12 ">
                    <div id="mensajeFormIngresoUsuario"> </div>
                    <form onKeypress="if(event.keyCode == 13) event.returnValue = false;"  onsubmit="return validarIngresoUsuario(this)" id="formIngresoUsuario" method="post" action="<?php echo $this->basePath();?>/usuario/ingresarusuario">
                            
                        <div class="form-group col-lg-5">
                            <label for="identificacion">IDENTIFICACIÓN DE LA PERSONA</label>
                            <input onkeyup="filtrarUsuarioPorIdentificacion(event);" onkeydown="validarNumeros('identificacion');" maxlength="10" autocomplete="off" autofocus="" type="text" id="identificacion" name="identificacion" class="form-control">
                        </div>

                        <div class="form-group col-lg-1">
                        </div>
                        <div class="form-group col-lg-6" id="contenedorDatosPersona">
                        </div>
                    </form>                  
                </div>
            </div>
        </div>
    </section>
       <?php } ?>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row">
                <div id="mensajeTablaUsuarios">
                    
                </div>
                <div  class="col-lg-12">
                    <div id="contenedorTablaUsuarios"></div>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">

</script>
<script type="text/javascript">
$(document).ready(function(){
    cargandoUsuarios('#contenedorTablaUsuarios');
    obtenerUsuarios();
});

</script>


 <div class="example-modal">
        <div class="modal " id="modalModificarUsuario">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">MODIFICAR</h4>
              </div>
              <div class="modal-body">
                  <div id="mensajeModificarUsuario">
                      
                  </div>
                  <form method="post" action="<?php echo $this->basePath();?>/usuario/modificarusuario" id="contenedorModificarUsuario">
                      
                  </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-right btn-flat" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      </div>


 <div class="example-modal">
        <div class="modal " id="modalModificarEstadoUsuario">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">HABILITAR O DESHABILITAR USUARIO</h4>
              </div>
              <div class="modal-body">
                  <div id="mensajeModificarEstadoUsuario">
                      
                  </div>
                  <form method="post" action="<?php echo $this->basePath();?>/usuario/modificarestadousuario" id="contenedorModificarEstadoUsuario">
                      
                  </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-right btn-flat" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      </div>


 <div class="example-modal">
        <div class="modal " id="modalAdministrarModulos">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">ADMINISTRAR MÓDULOS</h4>
              </div>
              <div class="modal-body">
                  <div id="mensajeAdministrarModulos">
                      
                  </div>
                  <form method="post" action="<?php echo $this->basePath();?>/gestionarmodulosprivilegios/administrarmodulos" id="contenedorAdministrarModulos">
                      
                  </form>
                  <div id="contenedorTablaModulos" > </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-right btn-flat" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      </div>


<div class="example-modal">
        <div class="modal " id="modalAdministrarPrivilegios">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">ADMINISTRAR PRIVILEGIOS</h4>
              </div>
              <div class="modal-body">
                  <div id="mensajeAdministrarPrivilegios">
                      
                  </div>
                  <form method="post" id="contenedorAdministrarPrivilegios">
                      
                  </form>
                  <div id="contenedorTablaPrivilegios" > </div>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-right btn-flat" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      </div>