<?php
//estas librerias php son llamadas ya que contienen los metodos ajax para obtener y envias
//datos al respectivo controlador
$validacionPrivilegio = $this->validacionPrivilegio;
include ($_SERVER['DOCUMENT_ROOT'].$this->basePath().'/public/metodos/jss/usuarios/usuarios.php');
 
 ?>


<div class="content-wrapper" style="min-height: 1123px;">
    <br><br>
    <section class="content-header">
        <h1>
            Usuarios
            <small>SWGP</small>
        </h1>
    </section>
    
    <section class="content">
        <div class="box-body nav-tabs-custom">
            <div class="row">
                <div id="mensajeTablaUsuarios">
                    
                </div>
                <div  class="col-lg-12">
                    <div id="contenedorTablaUsuarios"></div>
                </div>
            </div>
        </div>
    </section>
</div>
<script type="text/javascript">

</script>
<script type="text/javascript">
$(document).ready(function(){
    cargandoUsuarios('#contenedorTablaUsuarios');
    obtenerUsuarios();
});

</script>


 <div class="example-modal">
        <div class="modal " id="modalModificarUsuario">
          <div class="modal-dialog modal-md">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">MODIFICAR</h4>
              </div>
              <div class="modal-body">
                  <div id="mensajeModificarUsuario">
                      
                  </div>
                  <form method="post" action="<?php echo $this->basePath();?>/usuario/modificarusuario" id="contenedorModificarUsuario">
                      
                  </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-primary pull-right btn-flat" data-dismiss="modal">Cerrar</button>
              </div>
            </div>
          </div>
        </div>
      </div>